import { type AppType } from "next/app";
import { api } from "~/utils/api";
import "~/styles/bootstrap.min.css";
import Head from "next/head";
// import { useRouter } from "next/router";

const MyApp: AppType = ({ Component, pageProps }) => {
  // const router = useRouter();
  // if (router.pathname.startsWith("/admin")) {
  //   return <Component {...pageProps} />;
  // }

  return (
    <>
      <Head>
        <title>宝子链接</title>
        <meta charSet="UTF-8" />
        <meta name="description" content="Generated by create-t3-app" />
        {/* <link rel="stylesheet" type="text/css" href="custom.css" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="d-flex text-center text-bg-dark">
        <div className="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column m-5">
          <Component {...pageProps} />
        </div>
      </div>
    </>
  );
};

export default api.withTRPC(MyApp);
