import { type AppType } from "next/app";
import "~/styles/bootstrap.min.css";
import Head from "next/head";
import { ClerkProvider } from "@clerk/nextjs";

const MyApp: AppType = ({ Component, pageProps }) => {
  return (
    <>
      <Head>
        <title>宝子链接</title>
        <meta charSet="UTF-8" />
        <meta name="description" content="Generated by create-t3-app" />
        {/* <link rel="stylesheet" type="text/css" href="custom.css" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ClerkProvider {...pageProps}>
        <div className="d-flex text-center text-bg-dark">
          <div className="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column m-5">
            <Component {...pageProps} />
          </div>
        </div>
      </ClerkProvider>
    </>
  );
};

export default MyApp;
