import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>宝子直播</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="d-flex h-100 text-center text-bg-dark">
        <div className="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column m-5">
          <div>
            <h1 className="title">Join the chat!</h1>
          </div>
          <div>
            <p className="lead">
              <a href="" className="btn btn-primary btn-lg fw-bold">
                Join
              </a>
            </p>
            <p className="lead">Or paste the link into a browser: ...</p>
            <p>Last updated: ...</p>
          </div>
        </div>
      </main>
    </>
  );
}
