import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Share Link App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container">
        <div>
          <h1 className="title">Join the chat!</h1>
        </div>
        <div>
          <p>a link here...</p>
          <p>Last updated: ...</p>
        </div>
      </main>
    </>
  );
}
